# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnXD5bz3KoQV2fNQNA4_OeXGRnRhIdqb
"""

import numpy as np
import pandas as pd

df=pd.DataFrame({'A':
                 [1,2,np.nan,4],
                 'B':[5,np.nan,np.nan,8],
                 'C':[10,20,30,40],
                 'D':[2,2,2,2]})


df.dropna(thresh=2)

df

df.dropna(axis=1)

df.fillna(value='FILL VALUE')

df.fillna(value='5')

df['A'].fillna(Value=0)

df['A'].fillna(df['A'].mean())

df.fillna(df.mean())

import numpy as np
import pandas as pd

df=pd.DataFrame({'A':
                 [1,2,4,4,5,5],
                 'B':[5,5,6,8,8,8],
                 'C':[10,20,30,40,30,40],
} )
df

df['B'].unique()

df['B'].nunique()

df.drop_duplicates()

df['New_Column']=df['A']*10
df

df['New_Row']=df['']*10
df